//! Build script: auto-discovers the embedded translation files.
//!
//! Every `lang/<locale>.json` in the crate root is compiled into the plugin
//! binary. Adding a new language file requires **no code changes** — just drop
//! the file into `lang/` and rebuild. The generated registry is included by
//! `src/i18n.rs` from `OUT_DIR`.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const FALLBACK_LOCALE: &str = "en_us";

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set");
    let lang_dir = Path::new(&manifest_dir).join("lang");

    // Re-run when any language file is added, removed or modified.
    println!("cargo:rerun-if-changed=lang");

    let entries = fs::read_dir(&lang_dir)
        .unwrap_or_else(|error| panic!("failed to scan {}: {error}", lang_dir.display()));
    let mut languages: BTreeMap<String, PathBuf> = BTreeMap::new();
    for entry in entries {
        let path = entry
            .unwrap_or_else(|error| panic!("failed to read a language directory entry: {error}"))
            .path();
        if !path.is_file()
            || path.extension().and_then(|extension| extension.to_str()) != Some("json")
        {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_else(|| panic!("language file name is not valid UTF-8: {}", path.display()));
        let locale = normalize_locale(stem);
        assert!(
            !locale.is_empty()
                && locale
                    .chars()
                    .all(|character| character.is_ascii_lowercase()
                        || character.is_ascii_digit()
                        || character == '_'),
            "invalid locale file name: {}",
            path.display()
        );
        if let Some(previous) = languages.insert(locale.clone(), path.clone()) {
            panic!(
                "language files {} and {} normalize to the same locale {locale}",
                previous.display(),
                path.display()
            );
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }

    assert!(
        languages.contains_key(FALLBACK_LOCALE),
        "lang/{FALLBACK_LOCALE}.json is required as the fallback catalog"
    );

    let mut out = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// Embedded language files: `(locale, json)` pairs, one per `lang/<locale>.json`.\n\
         pub const EMBEDDED_LANGS: &[(&str, &str)] = &[\n",
    );
    for (locale, file) in &languages {
        // Absolute path so `include_str!` resolves regardless of OUT_DIR location.
        out.push_str(&format!(
            "    ({locale:?}, include_str!({:?})),\n",
            file.display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set");
    let dest = Path::new(&out_dir).join("embedded_langs.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

fn normalize_locale(locale: &str) -> String {
    locale.trim().to_ascii_lowercase().replace('-', "_")
}
