//! Plugin translations loaded directly from JSON language files.
//!
//! Keeping the registry inside the plugin lets language files be discovered
//! purely by file name instead of maintaining a second locale-to-enum table in
//! Rust. Missing translations fall back to `en_us`, then to the raw key, so an
//! incomplete language file can never break a message.
//!
//! # Adding a language
//!
//! Drop a `lang/<locale>.json` file into the crate root and rebuild, or put one
//! into `<plugin data folder>/lang/<locale>.json` at runtime. No Rust source
//! changes are required. Embedded files are discovered by `build.rs`;
//! data-folder files are scanned on load and override individual embedded keys.

use pumpkin_plugin_api::text::TextComponent;
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::{LazyLock, OnceLock, RwLock};

/// Fallback if the configured server language cannot be read.
pub const FALLBACK_LOCALE: &str = "en_us";

// Auto-generated by build.rs: one entry per `lang/<locale>.json`.
include!(concat!(env!("OUT_DIR"), "/embedded_langs.rs"));

type Catalog = HashMap<String, String>;
type Catalogs = HashMap<String, Catalog>;

/// All translations known to the plugin. The lazy initializer is also usable
/// from `Plugin::metadata`, which Pumpkin requests before `on_load` provides a
/// data-folder path.
static TRANSLATIONS: LazyLock<RwLock<Catalogs>> = LazyLock::new(|| {
    let mut catalogs = HashMap::new();
    for (locale, json) in EMBEDDED_LANGS {
        if let Ok(catalog) = parse_catalog(json) {
            merge_catalog(&mut catalogs, locale, catalog);
        }
    }
    RwLock::new(catalogs)
});

/// Server-side language (from the `language` config option), used for
/// registration-time strings (command and permission descriptions) and
/// console feedback. Player-facing messages always use the player's own
/// client locale instead.
static SERVER_LOCALE: OnceLock<String> = OnceLock::new();

/// Selects the server locale and loads overrides found in
/// `<data_folder>/lang/<locale>.json`.
///
/// Files loaded later overwrite matching keys, so a partial data-folder file
/// can override embedded defaults without repeating the whole catalog. Must be
/// called once from `on_load` after the config is initialized.
pub fn init(data_folder: &str) {
    let language = crate::config::CONFIG
        .read()
        .map(|config| config.language.clone())
        .unwrap_or_else(|_| FALLBACK_LOCALE.to_string());
    let _ = SERVER_LOCALE.set(normalize_locale(&language));

    load_folder_overrides(data_folder);
}

/// The server-side language (config option `language`, default `en_us`).
#[must_use]
pub fn default_locale() -> &'static str {
    SERVER_LOCALE.get().map_or(FALLBACK_LOCALE, String::as_str)
}

/// Builds a translated text component for `key`, resolved in `locale`.
#[must_use]
pub fn tr(locale: &str, key: &str) -> TextComponent {
    TextComponent::text(&translate_str(locale, key))
}

/// Builds a translated text component with sequential `%s` substitution
/// arguments.
#[must_use]
pub fn tr_with(locale: &str, key: &str, args: Vec<String>) -> TextComponent {
    TextComponent::text(&translate_str_with(locale, key, &args))
}

/// Resolves `key` to a plain translated string, for APIs that take raw
/// strings instead of text components (e.g. command and permission
/// descriptions, Bedrock kick messages).
#[must_use]
pub fn translate_str(locale: &str, key: &str) -> String {
    let locale = normalize_locale(locale);
    let key = key.to_ascii_lowercase();
    let catalogs = TRANSLATIONS
        .read()
        .unwrap_or_else(std::sync::PoisonError::into_inner);

    catalogs
        .get(&locale)
        .and_then(|catalog| catalog.get(&key))
        .or_else(|| {
            catalogs
                .get(FALLBACK_LOCALE)
                .and_then(|catalog| catalog.get(&key))
        })
        .cloned()
        .unwrap_or(key)
}

/// Resolves a translation and substitutes Java-style `%s` / `%N$s`
/// placeholders. Extra arguments are ignored and placeholders without a
/// matching argument remain visible, which makes malformed community
/// translations diagnosable instead of silently deleting text.
#[must_use]
pub fn translate_str_with(locale: &str, key: &str, args: &[String]) -> String {
    interpolate(&translate_str(locale, key), args)
}

/// Loads `lang/<locale>.json` overrides from the plugin data folder.
fn load_folder_overrides(data_folder: &str) {
    let normalized = data_folder.replace('\\', "/");
    if normalized.is_empty() {
        return;
    }

    let dir = Path::new(&normalized).join("lang");
    let Ok(entries) = fs::read_dir(&dir) else {
        return; // No overrides folder: perfectly normal.
    };

    let mut paths: Vec<_> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.is_file()
                && path.extension().and_then(|extension| extension.to_str()) == Some("json")
        })
        .collect();
    paths.sort();

    for path in paths {
        let Some(locale) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        let locale = normalize_locale(locale);
        if locale.is_empty() {
            continue;
        }

        match fs::read_to_string(&path) {
            Ok(json) => match parse_catalog(&json) {
                Ok(catalog) => {
                    let mut catalogs = TRANSLATIONS
                        .write()
                        .unwrap_or_else(std::sync::PoisonError::into_inner);
                    merge_catalog(&mut catalogs, &locale, catalog);
                    drop(catalogs);

                    tracing::info!(
                        "{}",
                        translate_str_with(
                            default_locale(),
                            "log.i18n.loaded",
                            &[locale.clone(), path.display().to_string()],
                        )
                    );
                }
                Err(err) => tracing::warn!(
                    "{}",
                    translate_str_with(
                        default_locale(),
                        "log.i18n.parse_failed",
                        &[path.display().to_string(), err.to_string()],
                    )
                ),
            },
            Err(err) => tracing::warn!(
                "{}",
                translate_str_with(
                    default_locale(),
                    "log.i18n.read_failed",
                    &[path.display().to_string(), err.to_string()],
                )
            ),
        }
    }
}

fn normalize_locale(locale: &str) -> String {
    locale.trim().to_ascii_lowercase().replace('-', "_")
}

fn parse_catalog(json: &str) -> serde_json::Result<Catalog> {
    let catalog: Catalog = serde_json::from_str(json)?;
    Ok(catalog
        .into_iter()
        .map(|(key, value)| (key.to_ascii_lowercase(), value))
        .collect())
}

fn merge_catalog(catalogs: &mut Catalogs, locale: &str, catalog: Catalog) {
    catalogs
        .entry(normalize_locale(locale))
        .or_default()
        .extend(catalog);
}

fn interpolate(template: &str, args: &[String]) -> String {
    let chars: Vec<char> = template.chars().collect();
    let mut output = String::with_capacity(template.len());
    let mut index = 0;
    let mut next_sequential = 0;

    while index < chars.len() {
        if chars[index] != '%' || index + 1 >= chars.len() {
            output.push(chars[index]);
            index += 1;
            continue;
        }

        if chars[index + 1] == '%' {
            output.push('%');
            index += 2;
            continue;
        }

        let placeholder_start = index;
        let (argument_index, placeholder_end) = if chars[index + 1] == 's' {
            let argument_index = next_sequential;
            next_sequential += 1;
            (Some(argument_index), index + 2)
        } else {
            let mut cursor = index + 1;
            while cursor < chars.len() && chars[cursor].is_ascii_digit() {
                cursor += 1;
            }
            if cursor > index + 1
                && cursor + 1 < chars.len()
                && chars[cursor] == '$'
                && chars[cursor + 1] == 's'
            {
                let number: String = chars[index + 1..cursor].iter().collect();
                (
                    number
                        .parse::<usize>()
                        .ok()
                        .and_then(|number| number.checked_sub(1)),
                    cursor + 2,
                )
            } else {
                output.push('%');
                index += 1;
                continue;
            }
        };

        if let Some(argument) = argument_index.and_then(|position| args.get(position)) {
            output.push_str(argument);
        } else {
            output.extend(&chars[placeholder_start..placeholder_end]);
        }
        index = placeholder_end;
    }

    output
}

#[cfg(test)]
mod tests {
    use super::{
        EMBEDDED_LANGS, FALLBACK_LOCALE, interpolate, load_folder_overrides, normalize_locale,
        parse_catalog, translate_str,
    };
    use std::collections::{HashMap, HashSet};
    use std::fs;
    use std::path::{Path, PathBuf};

    fn parse(json: &str) -> HashMap<String, String> {
        parse_catalog(json).unwrap_or_else(|e| panic!("invalid language file: {e}"))
    }

    #[test]
    fn embedded_language_files_are_valid_and_non_empty() {
        // The runtime ignores malformed embedded catalogs so metadata can
        // still be returned; fail loudly in tests instead.
        assert!(
            !EMBEDDED_LANGS.is_empty(),
            "no embedded language files found"
        );
        for (locale, json) in EMBEDDED_LANGS {
            let map = parse(json);
            assert!(!map.is_empty(), "{locale} contains no translations");
        }
    }

    #[test]
    fn every_locale_defines_the_same_keys() {
        let (_, reference) = EMBEDDED_LANGS
            .iter()
            .find(|(locale, _)| *locale == "en_us")
            .expect("en_us.json is the fallback and must exist");
        let mut reference: Vec<_> = parse(reference).keys().cloned().collect();
        reference.sort_unstable();

        for (locale, json) in EMBEDDED_LANGS {
            let mut keys: Vec<_> = parse(json).keys().cloned().collect();
            keys.sort_unstable();
            assert_eq!(
                keys, reference,
                "translation keys in {locale} drifted from en_us"
            );
        }
    }

    #[test]
    fn every_locale_preserves_placeholder_arguments() {
        let (_, reference) = EMBEDDED_LANGS
            .iter()
            .find(|(locale, _)| *locale == FALLBACK_LOCALE)
            .expect("en_us.json is the fallback and must exist");
        let reference = parse(reference);

        for (locale, json) in EMBEDDED_LANGS {
            let catalog = parse(json);
            for (key, reference_value) in &reference {
                let value = catalog.get(key).expect("key sets are checked separately");
                assert_eq!(
                    placeholder_arguments(value),
                    placeholder_arguments(reference_value),
                    "translation placeholders for {key} differ in {locale}"
                );
            }
        }
    }

    #[test]
    fn generated_registry_matches_language_directory() {
        let mut discovered: Vec<_> = fs::read_dir(concat!(env!("CARGO_MANIFEST_DIR"), "/lang"))
            .expect("lang directory must exist")
            .flatten()
            .map(|entry| entry.path())
            .filter(|path| {
                path.is_file()
                    && path.extension().and_then(|extension| extension.to_str()) == Some("json")
            })
            .filter_map(|path| {
                path.file_stem()
                    .and_then(|stem| stem.to_str())
                    .map(normalize_locale)
            })
            .collect();
        discovered.sort_unstable();

        let embedded: Vec<_> = EMBEDDED_LANGS
            .iter()
            .map(|(locale, _)| (*locale).to_owned())
            .collect();
        assert_eq!(
            embedded, discovered,
            "build.rs did not discover every language file"
        );
    }

    #[test]
    fn every_translation_key_used_by_rust_exists_in_fallback_catalog() {
        const PREFIXES: &[&str] = &[
            "plugin.",
            "command.",
            "message.",
            "kick.",
            "permission.",
            "category.",
            "error.",
            "log.",
        ];

        let (_, fallback) = EMBEDDED_LANGS
            .iter()
            .find(|(locale, _)| *locale == FALLBACK_LOCALE)
            .expect("en_us.json is the fallback and must exist");
        let fallback = parse(fallback);
        let mut files = Vec::new();
        collect_rust_files(
            &Path::new(env!("CARGO_MANIFEST_DIR")).join("src"),
            &mut files,
        );

        let mut used_keys = HashSet::new();
        for path in files {
            let source = fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
            for candidate in source.split('"').skip(1).step_by(2) {
                if PREFIXES
                    .iter()
                    .any(|prefix| candidate.len() > prefix.len() && candidate.starts_with(prefix))
                {
                    used_keys.insert(candidate.to_ascii_lowercase());
                }
            }
        }

        let missing: Vec<_> = used_keys
            .into_iter()
            .filter(|key| !fallback.contains_key(key))
            .collect();
        assert!(
            missing.is_empty(),
            "missing fallback translation keys: {missing:?}"
        );
    }

    #[test]
    fn local_registry_translates_and_falls_back_to_english() {
        assert_eq!(
            translate_str("zh-CN", "command.join.missing_password"),
            "缺少密码"
        );
        assert_eq!(
            translate_str("unknown_locale", "command.join.missing_password"),
            "Missing password"
        );
        assert_eq!(translate_str("zh_cn", "unknown.key"), "unknown.key");
    }

    #[test]
    fn runtime_folder_scanner_accepts_a_new_locale_without_registration() {
        let root = std::env::temp_dir().join(format!("i18n-runtime-test-{}", uuid::Uuid::new_v4()));
        let lang_dir = root.join("lang");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&lang_dir).expect("test lang directory should be created");
        fs::write(
            lang_dir.join("test_locale.json"),
            r#"{"runtime.only":"Loaded dynamically"}"#,
        )
        .expect("test translation file should be written");

        load_folder_overrides(root.to_str().expect("test path should be UTF-8"));

        assert_eq!(
            translate_str("test-locale", "runtime.only"),
            "Loaded dynamically"
        );
        assert_eq!(
            translate_str("test_locale", "command.join.missing_password"),
            "Missing password"
        );
        fs::remove_dir_all(root).expect("test translation directory should be removed");
    }

    #[test]
    fn interpolation_supports_sequential_and_indexed_placeholders() {
        let args = vec!["one".to_string(), "two".to_string()];
        assert_eq!(
            interpolate("%2$s then %s; 100%%; missing %3$s", &args),
            "two then one; 100%; missing %3$s"
        );
    }

    fn collect_rust_files(directory: &Path, files: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(directory).expect("source directory must be readable") {
            let path = entry.expect("source entry must be readable").path();
            if path.is_dir() {
                collect_rust_files(&path, files);
            } else if path.extension().and_then(|extension| extension.to_str()) == Some("rs") {
                files.push(path);
            }
        }
    }

    fn placeholder_arguments(template: &str) -> Vec<usize> {
        let chars: Vec<_> = template.chars().collect();
        let mut arguments = Vec::new();
        let mut index = 0;
        let mut next_sequential = 0;

        while index + 1 < chars.len() {
            if chars[index] != '%' {
                index += 1;
                continue;
            }
            if chars[index + 1] == '%' {
                index += 2;
                continue;
            }
            if chars[index + 1] == 's' {
                arguments.push(next_sequential);
                next_sequential += 1;
                index += 2;
                continue;
            }

            let mut cursor = index + 1;
            while cursor < chars.len() && chars[cursor].is_ascii_digit() {
                cursor += 1;
            }
            if cursor > index + 1
                && cursor + 1 < chars.len()
                && chars[cursor] == '$'
                && chars[cursor + 1] == 's'
            {
                let number: String = chars[index + 1..cursor].iter().collect();
                if let Some(argument) = number
                    .parse::<usize>()
                    .ok()
                    .and_then(|number| number.checked_sub(1))
                {
                    arguments.push(argument);
                }
                index = cursor + 2;
            } else {
                index += 1;
            }
        }

        arguments.sort_unstable();
        arguments
    }
}
